### PR TITLE
Add support for React v17

### PR DESCRIPTION
**Pull request by jaytarr**
Adding support for React v17. I have been running it in v17 for a long time with no issues.

### CODE REVIEW

**Comment by jlucfarias** [comment]
@codeep there is a blocking issue to get this merged?

**Comment by visualjeff** [comment]
Any updates on this?   

I'd like to use this with React 17.

**Comment by visualjeff** [comment]
@codeep and @jlucfarias Any chance on getting this merged?

**Comment by jlucfarias** [comment]
@visualjeff i don't think so. @codeep do not answer and the last activity of this repo was at 2020 that I think this may be considered as abandoned. I think you'll need to use an alternative

**Comment by visualjeff** [comment]
Thank you narek118!

Can we publish a release?   BTW,  I wouldn't think this would be a breaking change.

**Comment by fredrikkarlsson-pervanovo** [comment]
@narek118 When will 2.1.0 be published on npm?

**Pull request merged**
