### PR TITLE
Bug fix: "execute" type checking

### PR DESCRIPTION
**Pull request by sedlukha**
There is a bug if you try to load the page with reCaptcha after hard refresh:
> TypeError: window.grecaptcha.execute is not a function

Not sure about the reason for this problem, but everything works fine after "execute" type checking.

### CODE REVIEW

**Comment by dachinat** [comment]
Can this be merged?

**Comment by narek118** [comment]
@sedlukha Please fix the conflicts

**Comment by sedlukha** [comment]
> @sedlukha Please fix the conflicts

check this out

**Comment by MogilevichDmitry** [comment]
Guys, please merge this PR

**Comment by fabiovalse** [comment]
The merge is really needed. On slow connection, _"TypeError: window.grecaptcha.execute is not a function"_ is always thrown. It seems that the ReCaptcha component is rendered before the library is actually ready to be used.

**Comment by fabiovalse** [comment]
Are you planning to release a 1.0.3 version on npm?

**Pull request merged**
